2022-10-04 14:17:23,582 INFO    MainThread:16690 [wandb_setup.py:_flush():69] setting env: {}
2022-10-04 14:17:23,583 INFO    MainThread:16690 [wandb_setup.py:_flush():69] setting login settings: {}
2022-10-04 14:17:23,583 INFO    MainThread:16690 [wandb_init.py:_log_setup():342] Logging user logs to /home/data_sapiens/programs/projects/graphormer/notebooks/wandb/run-20221004_141723-300qwu5e/logs/debug.log
2022-10-04 14:17:23,583 INFO    MainThread:16690 [wandb_init.py:_log_setup():343] Logging internal logs to /home/data_sapiens/programs/projects/graphormer/notebooks/wandb/run-20221004_141723-300qwu5e/logs/debug-internal.log
2022-10-04 14:17:23,585 INFO    MainThread:16690 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f088195b9a0>
2022-10-04 14:17:23,587 INFO    MainThread:16690 [wandb_init.py:init():375] calling init triggers
2022-10-04 14:17:23,587 INFO    MainThread:16690 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'device': 'cpu', 'adamw': {'lr': 0.001, 'weight_decay': 0.0001}, 'epochs': 500, 'scheduler': {'max_lr': 0.001, 'anneal_strategy': 'linear', 'pct_start': 0.1, 'total_steps': 27000}, 'run_evaluation': True, 'log_steps': 20, 'eval_steps': 100, 'max_grad_norm': 3.0, 'model': {'node_dim': 64, 'edge_dim': 1, 'num_classes': 100, 'embedding_dim': 64, 'n_encoders': 3}, 'random_state': 42, 'batch_size': 64, 'wandb': {'entity': 'broccoliman', 'project': 'Dvoryanin'}, 'total_steps': 27000}
2022-10-04 14:17:23,588 INFO    MainThread:16690 [wandb_init.py:init():424] starting backend
2022-10-04 14:17:23,588 INFO    MainThread:16690 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-04 14:17:23,621 INFO    MainThread:16690 [backend.py:ensure_launched():135] starting backend process...
2022-10-04 14:17:23,643 INFO    MainThread:16690 [backend.py:ensure_launched():139] started backend process with pid: 30152
2022-10-04 14:17:23,645 INFO    MainThread:16690 [wandb_init.py:init():429] backend started and connected
2022-10-04 14:17:23,715 INFO    MainThread:16690 [wandb_run.py:_label_probe_notebook():815] probe notebook
2022-10-04 14:17:23,715 INFO    MainThread:16690 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-10-04 14:17:23,716 INFO    MainThread:16690 [wandb_init.py:init():477] updated telemetry
2022-10-04 14:17:23,716 INFO    MainThread:16690 [wandb_init.py:init():500] communicating current version
2022-10-04 14:17:25,212 INFO    MainThread:16690 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.13.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-04 14:17:25,214 INFO    MainThread:16690 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2022-10-04 14:17:25,728 INFO    MainThread:16690 [wandb_init.py:init():540] starting run threads in backend
2022-10-04 14:17:29,333 INFO    MainThread:16690 [wandb_run.py:_console_start():1601] atexit reg
2022-10-04 14:17:29,334 INFO    MainThread:16690 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2022-10-04 14:17:29,334 INFO    MainThread:16690 [wandb_run.py:_redirect():1512] Wrapping output streams.
2022-10-04 14:17:29,335 INFO    MainThread:16690 [wandb_run.py:_redirect():1536] Redirects installed.
2022-10-04 14:17:29,335 INFO    MainThread:16690 [wandb_init.py:init():565] run started, returning control to user process
2022-10-04 14:17:29,335 INFO    MainThread:16690 [wandb_watch.py:watch():43] Watching
2022-10-04 14:17:29,358 INFO    MainThread:16690 [wandb_init.py:_pause_backend():256] pausing backend
2022-10-04 14:17:29,358 INFO    MainThread:16690 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2022-10-04 14:17:47,022 INFO    MainThread:16690 [wandb_init.py:_resume_backend():265] resuming backend
2022-10-04 14:17:47,024 INFO    MainThread:16690 [wandb_init.py:_pause_backend():256] pausing backend
2022-10-04 14:17:47,024 INFO    MainThread:16690 [jupyter.py:save_ipynb():298] not saving jupyter notebook
